# Generated by Django 5.1 on 2024-11-22 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("surveys", "0001_initial"),
        ("websites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionwebsite",
            name="website",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="websites.website"
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="questions",
            field=models.ManyToManyField(
                through="surveys.QuestionSurvey", to="surveys.question"
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="selected_website",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="websites.website",
            ),
        ),
        migrations.AddField(
            model_name="questionsurvey",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="surveys.survey"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="theme",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="surveys.theme",
            ),
        ),
    ]
