# Generated by Django 5.1 on 2024-11-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("studio", models.CharField(max_length=100)),
                ("link", models.URLField(max_length=250)),
                ("thumb", models.FileField(upload_to="")),
                ("text", models.TextField()),
                ("publication_date", models.DateField()),
                ("lang", models.CharField(max_length=3)),
            ],
        ),
    ]
