# Generated by Django 5.1 on 2024-11-03 21:51

from os.path import join

from django.db import migrations
from apps.migration.utils import fetch_data_from_mysql


def create_glossary_func(apps, _schema_editor):
    Glossary = apps.get_model("glossary", "Glossary")
    Count = apps.get_model("glossary", "Count")
    glossary_objects = []
    glossaries = fetch_data_from_mysql("porn_glossaryterm")
    for glossary in glossaries:
        glossary_objects.append(
            Glossary(
                id=glossary.id,
                slug=glossary.slug,
                name=glossary.labelEN,
                name_en=glossary.labelEN,
                name_fr=glossary.labelFR,
                type=glossary.type,
                definition=glossary.definitionEN,
                definition_en=glossary.definitionEN,
                definition_fr=glossary.definitionFR,
                meaning=glossary.signification,
                picture=join("img/glossary", glossary.illustration)
                if glossary.illustration
                else "",
                publication_date=glossary.publicationdate,
                count=Count.objects.create(up=glossary.up, down=glossary.down),
                lang=glossary.lang,
            )
        )
    Glossary.objects.bulk_create(glossary_objects)


def delete_glossary_func(apps, _schema_editor):
    Glossary = apps.get_model("glossary", "Glossary")
    glossaries = fetch_data_from_mysql("porn_glossaryterm")
    Glossary.objects.filter(id__in=[r.id for r in glossaries]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("glossary", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_glossary_func, delete_glossary_func, atomic=True),
    ]
