# Generated by Django 5.1 on 2024-11-03 07:05

from django.db import migrations
from apps.migration.utils import fetch_data_from_mysql
from os.path import join


def create_websites_func(apps, _schema_editor):
    Deal = apps.get_model("websites", "Deal")
    Category = apps.get_model("websites", "Category")
    Website = apps.get_model("websites", "Website")
    website_objs = []
    websites = fetch_data_from_mysql("porn_site")
    for website in websites:
        website_objs.append(
            Website(
                id=website.id,
                slug=website.slug,
                name=website.name,
                url=website.url,
                icon=join("img/logosites", website.icon),
                screen=join("img/screensites", website.screen),
                is_direct_link=True if website.isdirectlink == 1 else False,
                description=website.descriptionEN,
                description_en=website.descriptionEN,
                description_fr=website.descriptionFR,
                category=Category.objects.get(id=website.category_id),
                creation_date=website.updatedate,
                update_date=website.updatedate,
                end_date=website.enddate,
                click=website.click,
                deal=Deal.objects.get(id=website.deal_id) if website.deal_id else None,
            )
        )
    Website.objects.bulk_create(website_objs)


def delete_websites_func(apps, _schema_editor):
    Website = apps.get_model("websites", "Website")
    websites = fetch_data_from_mysql("porn_site")
    Website.objects.filter(id__in=[r.id for r in websites]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("websites", "0003_migrate_websites_deal"),
    ]

    operations = [
        migrations.RunPython(create_websites_func, delete_websites_func),
    ]
