# Generated by Django 5.1 on 2024-11-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0001_initial"),
        ("websites", "0004_migrate_websites_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="questions",
            field=models.ManyToManyField(
                through="surveys.QuestionWebsite", to="surveys.question"
            ),
        ),
    ]
