# Generated by Django 5.1 on 2024-11-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("websites", "0004_migrate_websites_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="website",
            name="creation_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="website",
            name="update_date",
            field=models.DateField(auto_now=True),
        ),
    ]
