# Generated by Django 5.1 on 2024-12-06 09:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("websites", "0005_alter_website_creation_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
    ]
