# Generated by Django 5.1 on 2024-11-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("websites", "0005_website_questions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.FileField(max_length=150, upload_to="img/iconcategories"),
        ),
    ]
