# Generated by Django 5.1 on 2024-11-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("websites", "0006_alter_category_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="website",
            name="icon",
            field=models.FileField(max_length=150, upload_to="img/logosites"),
        ),
        migrations.AlterField(
            model_name="website",
            name="screen",
            field=models.FileField(max_length=150, upload_to="img/screensites"),
        ),
    ]
