# Generated by Django 5.1 on 2025-01-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0002_migrate_videos_video"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.AlterField(
            model_name="video",
            name="publication_date",
            field=models.DateField(db_index=True),
        ),
    ]
