from .upload_to_according_to_type import upload_to_according_to_type
from .upload_to_according_to_fake_of_real import upload_to_according_to_fake_of_real

__all__ = ["upload_to_according_to_type", "upload_to_according_to_fake_of_real"]
