# Generated by Django 5.1 on 2024-11-27 19:33

from django.db import migrations

DEFAULT_TOPLINKS = [
    {
        "label": "UNDRESS AI 🔥",
        "link": "https://undress.cc/?ref=pornator",
        "lang": "en",
        "position": 0,
    },
    {
        "label": "LIVE CAMS",
        "link": "https://ptosrd.com/?siteId=jasmin&categoryName=&pageName=home&performerName=&prm[psid]=thepornator&prm[pstool]=205_1&prm[psprogram]=revs&prm[campaign_id]=&subAffId={SUBAFFID}&filters=",
        "lang": "en",
        "position": 1,
    },
    {
        "label": "BRAZZERS",
        "link": "https://landing.brazzersnetwork.com/?ats=eyJhIjo3NTY5OTEsImMiOjYwOTEyMDQxLCJuIjoxNCwicyI6OTAsImUiOjg4MDMsInAiOjExfQ==",
        "lang": "en",
        "position": 2,
    },
    {
        "label": "DEEPFAKE",
        "link": "https://www.bestfaceswap.ai/?utm_source=tpnator&utm_campaign=list",
        "lang": "en",
        "position": 3,
    },
    {
        "label": "UNDRESS AI 🔥",
        "link": "https://undress.cc/?ref=pornator",
        "lang": "fr",
        "position": 0,
    },
    {
        "label": "WEBCAMS",
        "link": "https://ptosrd.com/?siteId=jasmin&categoryName=&pageName=home&performerName=&prm[psid]=thepornator&prm[pstool]=205_1&prm[psprogram]=revs&prm[campaign_id]=&subAffId={SUBAFFID}&filters=",
        "lang": "fr",
        "position": 1,
    },
    {
        "label": "PLAN CUL",
        "link": "https://k.related-dating.com/?abc=d378b834d74605b5&xa=n&acme=wid.91384&media=display",
        "lang": "fr",
        "position": 2,
    },
    {
        "label": "DEEPFAKE",
        "link": "https://www.bestfaceswap.ai/?utm_source=tpnator&utm_campaign=list",
        "lang": "fr",
        "position": 3,
    },
]


def create_default_top_link(apps, _schema_editor):
    TopLink = apps.get_model("ads", "TopLink")
    top_link_objs = [TopLink(**top_link) for top_link in DEFAULT_TOPLINKS]
    TopLink.objects.bulk_create(top_link_objs)


def delete_default_top_link(apps, _schema_editor):
    TopLink = apps.get_model("ads", "TopLink")
    TopLink.objects.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0002_create_ads_from_source"),
    ]

    operations = [
        migrations.RunPython(create_default_top_link, delete_default_top_link)
    ]
