# Generated by Django 5.1 on 2024-11-04 09:58

from django.db import migrations
from apps.migration.utils import fetch_data_from_mysql


def create_trending_searches_func(apps, _schema_editor):
    TrendingSearches = apps.get_model("trends", "TrendingSearches")
    trending_searches_objects = []
    trending_searches = fetch_data_from_mysql("porn_trendingsearches")
    for trending_search in trending_searches:
        trending_searches_objects.append(
            TrendingSearches(
                id=trending_search.id,
                request=trending_search.request,
                date=trending_search.date,
                nb_result=trending_search.nb_results,
                lang=trending_search.lang,
            )
        )
    TrendingSearches.objects.bulk_create(trending_searches_objects)


def delete_trending_searches_func(apps, _schema_editor):
    TrendingSearches = apps.get_model("trends", "TrendingSearches")
    trending_searches = fetch_data_from_mysql("porn_trendingsearches")
    TrendingSearches.objects.filter(id__in=[r.id for r in trending_searches]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("trends", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            create_trending_searches_func, delete_trending_searches_func
        ),
    ]
