# Generated by Django 5.1 on 2024-11-05 19:17

from django.db import migrations, models
from django.utils.text import slugify


def create_slug_func(apps, _schema_editor):
    TrendingSearches = apps.get_model("trends", "trendingsearches")
    for trend in TrendingSearches.objects.all():
        trend.slug = slugify(trend.request.strip())
        trend.save()


class Migration(migrations.Migration):
    dependencies = [
        ("trends", "0002_migrate_statistics_trending_searches"),
    ]

    operations = [
        migrations.AddField(
            model_name="trendingsearches",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.RunPython(create_slug_func, migrations.RunPython.noop),
    ]
