# Generated by Django 5.1 on 2025-01-07 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0002_migrate_stories_stories"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="story",
            options={"verbose_name_plural": "stories"},
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.ImageField(upload_to="img/stories")),
                (
                    "blog",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stories.story",
                    ),
                ),
            ],
        ),
    ]
