# Generated by Django 5.1 on 2024-11-22 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True)),
                ("name", models.CharField(max_length=50)),
                ("name_en", models.CharField(max_length=50, null=True)),
                ("name_fr", models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Count",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("likes", models.PositiveIntegerField(default=0)),
                ("photos", models.PositiveIntegerField(default=0)),
                ("videos", models.PositiveIntegerField(default=0)),
                ("posts", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Website",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField(max_length=100)),
                ("image", models.ImageField(upload_to="img/logomodelsites")),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=100)),
                ("pseudo", models.CharField(max_length=100)),
                ("photo", models.URLField(max_length=1500)),
                ("description", models.TextField(max_length=500)),
                ("price", models.CharField(max_length=500)),
                ("local_photo", models.ImageField(upload_to="img/photomodels")),
                ("url", models.URLField(max_length=250)),
                ("categories", models.ManyToManyField(to="porn_models.category")),
                (
                    "counts",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="porn_models.count",
                    ),
                ),
                (
                    "website",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="porn_models.website",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(1, "Ok"), (0, "Not Found"), (-1, "Error")],
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="main_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="porn_models.profile",
            ),
        ),
    ]
