# Generated by Django 5.1 on 2024-12-06 09:56

from django.db import migrations

SYNONYMS = {
    "camgirl": ["cam"],
    "curvy": ["voluptuous", "bbw"],
    "tattooed": ["tatoo"],
    "jacquieetmichel": ["jacquie"],
    "foot": ["feet"],
    "fetish": ["fetichis", "fétich"],
    "redhead": ["rouge", "red head"],
    "dominated": ["dominée", "soumis"],
    "trans": ["shemale"],
    "arab": ["tunis", "maroc"],
    "hairy": ["poil"],
    "latina": ["hispanic", "latin"],
    "gay": ["homo"],
    "squirter": ["fontaine", "squirt"],
    "bigass": ["big ass", "big butt"],
    "bigtits": ["big boobs", "big breasts"],
    "black": ["ebony"],
    "horny": ["chaleur"],
    "anal": ["sodomie"],
    "granny": ["mamie"],
    "athletic": ["sport"],
}


def add_synonyms(apps, _schema_editor):
    Category = apps.get_model("porn_models", "Category")
    for slug, synonyms in SYNONYMS.items():
        category = Category.objects.get(slug=slug)
        category.synonyms = synonyms
        category.save(update_fields=["synonyms"])


def remove_synonyms(apps, _schema_editor):
    Category = apps.get_model("porn_models", "Category")
    Category.objects.all().update(synonyms=[])


class Migration(migrations.Migration):
    dependencies = [
        ("porn_models", "0003_alter_category_options_category_synonyms"),
    ]

    operations = [migrations.RunPython(add_synonyms, remove_synonyms)]
