# Generated by Django 5.1 on 2024-11-22 08:23

from apps.ai_pictures.utils import upload_to_according_to_type
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AiOrNotAi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveIntegerField(default=0)),
                ("ip", models.CharField(max_length=50)),
                ("date", models.DateTimeField(default=timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("name_en", models.CharField(max_length=50, null=True)),
                ("name_fr", models.CharField(max_length=50, null=True)),
                ("slug", models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("name_en", models.CharField(max_length=50, null=True)),
                ("name_fr", models.CharField(max_length=50, null=True)),
                ("slug", models.SlugField(blank=True)),
                ("icon", models.TextField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("funny", models.PositiveIntegerField(default=0)),
                ("sexy", models.PositiveIntegerField(default=0)),
                ("scary", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("title_en", models.CharField(max_length=200, null=True)),
                ("title_fr", models.CharField(max_length=200, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")], max_length=10
                    ),
                ),
                ("slug", models.CharField(max_length=100, null=True, blank=True)),
                ("publication_date", models.DateField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=250,
                        null=True,
                        upload_to=upload_to_according_to_type,
                    ),
                ),
                ("categories", models.ManyToManyField(to="ai_pictures.category")),
                ("external_url", models.URLField(null=True, blank=True)),
                ("created_at", models.DateTimeField(default=timezone.now)),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(1, "Ok"), (0, "Not Found"), (-1, "Error")],
                        null=True,
                    ),
                ),
            ],
        ),
    ]
