# Generated by Django 5.1 on 2024-11-22 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("websites", "0001_initial"),
        ("ai_pictures", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="websites.website",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="main_image_content",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ai_pictures.content",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="main_video_content",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="video_category_set",
                to="ai_pictures.content",
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="main_content",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="ai_pictures.content",
            ),
        ),
        migrations.AddField(
            model_name="content",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ai_pictures.country",
            ),
        ),
        migrations.AddField(
            model_name="content",
            name="note",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="ai_pictures.note"
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="contents",
            field=models.ManyToManyField(to="ai_pictures.content"),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(fields=["slug"], name="ai_pictures_slug_b46050_idx"),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(
                fields=["source"], name="ai_pictures_source__bafd1f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(
                fields=["publication_date"], name="ai_pictures_publica_42fc93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(fields=["type"], name="ai_pictures_type_8b72ea_idx"),
        ),
    ]
