# Generated by Django 5.1 on 2024-11-25 13:45

from apps.ai_pictures.utils import upload_to_according_to_fake_of_real
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_pictures", "0004_migrate_ai_pictures_ai_or_not_ai"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiOrNotAiImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(upload_to=upload_to_according_to_fake_of_real),
                ),
                ("is_real", models.BooleanField()),
                ("enabled", models.BooleanField()),
            ],
        ),
        migrations.RenameModel(
            old_name="AiOrNotAi",
            new_name="AiOrNotAiScore",
        ),
    ]
