# Generated by Django 5.1 on 2024-11-25 13:45
import os
from urllib.parse import urlparse

from django.db import migrations

from minio import Minio


def link_real_and_fake_images(apps, _schema_editor):
    AiOrNotAiImage = apps.get_model("ai_pictures", "AiOrNotAiImage")
    MINIO_ENDPOINT = urlparse(os.environ.get("MINIO_ENDPOINT_URL"))
    MINIO_ACCESS_KEY = os.environ.get("MINIO_ACCESS_KEY")
    MINIO_SECRET_KEY = os.environ.get("MINIO_SECRET_KEY")
    MINIO_BUCKET_NAME = os.environ.get("MINIO_BUCKET_NAME")
    minio_client = Minio(
        f"{MINIO_ENDPOINT.hostname}:{MINIO_ENDPOINT.port}",
        access_key=MINIO_ACCESS_KEY,
        secret_key=MINIO_SECRET_KEY,
        secure=False,
    )
    fakes = minio_client.list_objects(MINIO_BUCKET_NAME, prefix="img/aiornotai/fake/")
    for obj in fakes:
        if not obj.is_dir:
            _ = AiOrNotAiImage.objects.create(
                picture=obj.object_name, is_real=False, enabled=True
            )
    reals = minio_client.list_objects(MINIO_BUCKET_NAME, prefix="img/aiornotai/real/")
    for obj in reals:
        if not obj.is_dir:
            _ = AiOrNotAiImage.objects.create(
                picture=obj.object_name, is_real=True, enabled=True
            )


class Migration(migrations.Migration):
    dependencies = [
        ("ai_pictures", "0005_aiornotaiimage_rename_aiornotai_aiornotaiscore"),
    ]

    operations = [
        migrations.RunPython(link_real_and_fake_images, migrations.RunPython.noop)
    ]
