# Generated by Django 5.1 on 2025-01-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_pictures", "0006_aiornotai_images_adding"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "countries"},
        ),
        migrations.RenameIndex(
            model_name="content",
            new_name="ai_pictures_slug_b4f09e_idx",
            old_name="ai_pictures_slug_b46050_idx",
        ),
        migrations.AlterField(
            model_name="content",
            name="publication_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="content",
            name="slug",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="type",
            field=models.CharField(
                choices=[("image", "Image"), ("video", "Video")],
                db_index=True,
                max_length=10,
            ),
        ),
    ]
