# Generated by Django 5.1 on 2024-11-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrendingSearches",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("nb_result", models.PositiveIntegerField()),
                ("lang", models.CharField(max_length=10)),
            ],
        ),
    ]
